### ISSUE TITLE
Error in line 83 in Eventos

### ISSUE THREAD

**Issue by alair069** [BEcraft/SkyWarsBE#1]
[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'SkyWarsBE v1.0.0': Access to undeclared static property: SkyWars\Eventos\UnirseEvento::$handlerList on SkyWars\Eventos\Eventos
[Server thread/CRITICAL]: Error: "Access to undeclared static property: SkyWars\Eventos\UnirseEvento::$handlerList" (EXCEPTION) in "src/pocketmine/event/Event" at line 83

**Comment by BEcraft** [comment]
Are you trying to run this plugin on Steadfast?

**Comment by alair069** [comment]
No, PMMP 3.0.0-ALPHA11

**Comment by BEcraft** [comment]
Then try it on last pmmp's version and everything should be working fine
